# 使用官方 Nginx 镜像作为基础镜像
FROM nginx:latest

USER root

# 设置工作目录为 /usr/share/nginx/html，这是 Nginx 默认的静态文件目录
WORKDIR /usr/share/nginx/html

# 将构建的 Vue 应用静态文件复制到容器中的 Nginx 默认静态文件目录
COPY dist .

# 可以使用 COPY 指令复制自定义的 Nginx 配置文件（如果需要）
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 清除默认的 Nginx 配置文件（如果之前复制了自定义配置则不需要此步骤）
# RUN rm /etc/nginx/conf.d/default.conf


# 暴露 80 端口供外部访问
EXPOSE 8000


WORKDIR /opt/application

COPY run.sh .

RUN chmod +x /opt/application/run.sh

CMD /opt/application/run.sh

# 启动 Nginx 服务
# CMD ["nginx", "-g", "daemon off;"]